# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

# Install composer dependencies
install:
  - composer install

# Run script
script:
  - ./vendor/bin/simple-phpunit
